Travis CI: armhf sysroot update at 2016-11-06 08:38:03 UTC.

diff --git a/lib/apparmor/functions b/lib/apparmor/functions
--- a/lib/apparmor/functions
+++ b/lib/apparmor/functions
@@ -196,7 +196,7 @@ compare_and_save_debsums() {
 		saved_sums="${PROFILES_VAR}/.${pkg}.md5sums"
 
 		if [ -f "$sums" ] && \
-		   ! diff -q "$sums" "$saved_sums" 2>/dev/null ; then
+		   ! diff -q "$sums" "$saved_sums" 2>&1 >/dev/null ; then
 			cp -f "$sums" "$saved_sums"
 			return 1
 		fi
@@ -218,6 +218,53 @@ compare_previous_version() {
 			# snappy updates $previous elsewhere, so just return
 			return 1
 		fi
+	fi
+
+	return 0
+}
+
+# Checks to see if the current container is capable of having internal AppArmor
+# profiles that should be loaded. Callers of this function should have already
+# verified that they're running inside of a container environment with
+# something like `systemd-detect-virt --container`.
+#
+# The only known container environments capable of supporting internal policy
+# are LXD and LXC environment.
+#
+# Returns 0 if the container environment is capable of having its own internal
+# policy and non-zero otherwise.
+#
+# IMPORTANT: This function will return 0 in the case of a non-LXD/non-LXC
+# system container technology being nested inside of a LXD/LXC container that
+# utilized an AppArmor namespace and profile stacking. The reason 0 will be
+# returned is because .ns_stacked will be "yes" and .ns_name will still match
+# "lx[dc]-*" since the nested system container technology will not have set up
+# a new AppArmor profile namespace. This will result in the nested system
+# container's boot process to experience failed policy loads but the boot
+# process should continue without any loss of functionality. This is an
+# unsupported configuration that cannot be properly handled by this function.
+is_container_with_internal_policy() {
+	local ns_stacked_path="${AA_SFS}/.ns_stacked"
+	local ns_name_path="${AA_SFS}/.ns_name"
+	local ns_stacked
+	local ns_name
+
+	if ! [ -f "$ns_stacked_path" ] || ! [ -f "$ns_name_path" ]; then
+		return 1
+	fi
+
+	read -r ns_stacked < "$ns_stacked_path"
+	if [ "$ns_stacked" != "yes" ]; then
+		return 1
+	fi
+
+	# LXD and LXC set up AppArmor namespaces starting with "lxd-" and
+	# "lxc-", respectively. Return non-zero for all other namespace
+	# identifiers.
+	read -r ns_name < "$ns_name_path"
+	if [ "${ns_name#lxd-*}" = "$ns_name" ] && \
+	   [ "${ns_name#lxc-*}" = "$ns_name" ]; then
+		return 1
 	fi
 
 	return 0
